controllers/AbsentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Absent;
use app\models\AbsentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * AbsentController implements the CRUD actions for Absent model.
 */
class AbsentController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->username=="admin";
                        }
                    ],
                    [
                        'actions' => ['create', 'update'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->username=="admin" || Yii::$app->user->identity->username=="user" || Yii::$app->user->identity->username=="user1" || Yii::$app->user->identity->username=="user2";
                        }
                    ],
                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
        ];
    }

    /**
     * Lists all Absent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AbsentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Absent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Absent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Absent();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Absent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['employee/view', 'id' => $model->employee_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Absent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $employee_id = $model->employee_id;
        $model->delete();
        return $this->redirect(['employee/view', 'id' => $employee_id]);
    }

    /**
     * Finds the Absent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Absent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Absent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/CardController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Card;
use app\models\CardSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CardController implements the CRUD actions for Card model.
 */
class CardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Card models.
     * @return mixed
     */
    public function actionIndex()
    {
        $employeeModel = new \app\models\EmployeeSearch();
        $searchModel = new CardSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'employeeModel' => $employeeModel,
        ]);
    }

    /**
     * Displays a single Card model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Card model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Card();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Card model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Card model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Card model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Card the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Card::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/EmployeeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Employee;
use app\models\EmployeeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->username=="admin";
                        }
                    ],
					[
                        'actions' => ['create'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->username=="admin" || Yii::$app->user->identity->username=="user";
                        }
                    ],
                    [
                        'actions' => ['create-absent', 'update'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->username=="admin" || Yii::$app->user->identity->username=="user" || Yii::$app->user->identity->username=="user1" || Yii::$app->user->identity->username=="user2";
                        }
                    ],
                    [
                        'actions' => ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
        ];
    }

    /**
     * Lists all Employee models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmployeeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employee model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $searchModel = new \app\models\AbsentSearch();
        $searchModel->employee_id = $id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employee();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Absent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreateAbsent($id)
    {
        $model = new \app\models\Absent();
        $model->employee_id = $id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->employee_id]);
        }

        return $this->render('/absent/create', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/employee/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="col-md-6 employee-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'rank')->dropDownList($model::RANK_LIST, ['prompt'=>Yii::t('app', 'Select rank')]); ?>

    <?= $form->field($model, 'specialist')->dropDownList($model::SPECIALIST_LIST, ['prompt'=>Yii::t('app', 'Select specialist')]); ?>

    <?= $form->field($model, 'office')->dropDownList($model::OFFICE_LIST, ['prompt'=>Yii::t('app', 'Select office')]); ?>

    <?= $form->field($model, 'shift')->dropDownList($model::SHIFT_LIST, ['prompt'=>Yii::t('app', 'Select shift')]); ?>

    <?= $form->field($model, 'joining_date')->widget(DatePicker::classname(), [
            'options' => ['placeholder' => Yii::t('app', 'Select Joining Date')],
            'language' => 'ar',
            'removeButton' => false,
            //'convertFormat' => true,
            'pluginOptions' => [
                'format' => 'yyyy-mm-dd',
                'todayHighlight' => true
            ]
        ]) 
    ?>

    <?= $form->field($model, 'promotion_date')->widget(DatePicker::classname(), [
            'options' => ['placeholder' => Yii::t('app', 'Select Promotion Date')],
            'language' => 'ar',
            'removeButton' => false,
            //'convertFormat' => true,
            'pluginOptions' => [
                'format' => 'yyyy-mm-dd',
                'todayHighlight' => true
            ]
        ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employee/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EmployeeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employee-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'mobile') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'rank') ?>

    <?php // echo $form->field($model, 'specialist') ?>

    <?php // echo $form->field($model, 'office') ?>

    <?php // echo $form->field($model, 'joining_date') ?>

    <?php // echo $form->field($model, 'promotion_date') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employee/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = Yii::t('app', 'Create Employee');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Employee'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employee/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = Yii::t('app', 'Update Employee: {nameAttribute}', [
    'nameAttribute' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Employee'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="employee-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employee/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Employee */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Employee'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employee-view">

    <h1 class="no-print"><?= Html::encode($this->title) ?></h1>

    <p class="no-print">
        <?= Html::a(Yii::t('app', 'Create Absent'), ['create-absent', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a(Yii::t('app', 'Print'), '#', ['class' => 'btn btn-primary', 'id'=>'print-user-detail']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'id' => 'user-detail-grid',
        'attributes' => [
            //'id',
            'code',
            [
                'attribute' => 'rank',
                'value' => $model::RANK_LIST[$model->rank]
            ],
            'name',
            [
                'attribute' => 'mobile',
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ],
            [
                'attribute' => 'email',
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ],
            [
                'attribute' => 'specialist',
                'value' => $model::SPECIALIST_LIST[$model->specialist],
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ],
            [
                'attribute' => 'office',
                'value' => $model::OFFICE_LIST[$model->office],
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ],
            [
                'attribute' => 'shift',
                'value' => $model::SHIFT_LIST[$model->shift],
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ],
            [
                'attribute' => 'joining_date',
                'format' => ['date', 'php:d-m-Y'],
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ],
            [
                'attribute' => 'promotion_date',
                'format' => ['date', 'php:d-m-Y'],
                'contentOptions' => ['class' => 'no-print'],
                'captionOptions' => ['class' => 'no-print'],
            ]
        ],
    ]) ?>

</div>

<div class="absent-index">

<h1><?= Html::encode(Yii::t("app","Absent")) ?></h1>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
	'layout' => '{items}\n{pager}',
    'columns' => [
        ['class' => 'yii\grid\SerialColumn', 'header' => Yii::t('app', 'Number')],
        [
            'attribute' => 'absent_type',
            'value' => function ($model) {
                return $model::ABSENT_TYPE[$model->absent_type];
            },
            'filter' => \app\models\Absent::ABSENT_TYPE
        ],
        [
            'label' => Yii::t('app','Reason'),
            'attribute' => 'reason'
        ],
        [
            'attribute' => 'start_date',
            'format' => ['date', 'php:d-m-Y'],
            'filter' => \kartik\date\DatePicker::widget([
                'model'=>$searchModel,
                'attribute'=>'start_date',
                'language' => 'ar',
                'type' => \kartik\date\DatePicker::TYPE_INPUT,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]),
        ],
        [
            'attribute' => 'end_date',
            'format' => ['date', 'php:d-m-Y'],
            'filter' => \kartik\date\DatePicker::widget([
                'model'=>$searchModel,
                'attribute'=>'end_date',
                'language' => 'ar',
                'type' => \kartik\date\DatePicker::TYPE_INPUT,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]),
        ],
        'place',
        [
            'label' => 'المده',
            'value' => function ($model) {
                $day1 = new \DateTime($model->start_date);
                $day2 = new \DateTime($model->end_date);
                $interval = round(abs($day2->format('U') - $day1->format('U')) / (60*60*24));
                return $interval+1;
            },
            'filter' => \app\models\Absent::ABSENT_TYPE
        ],
        //'comment',
        [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => ['class' => 'no-print'],
            'header' => 'Actions',
            'headerOptions' => ['style' => 'color:#337ab7', 'class'=>'no-print'],
            'template' => '{view}{update}{delete}',
            'buttons' => [
                'view' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['absent/view', 'id'=>$model->id], [
                                'title' => Yii::t('app', 'absent-view'),
                    ]);
                },

                'update' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['absent/update', 'id'=>$model->id], [
                                'title' => Yii::t('app', 'absent-update'),
                    ]);
                },
                'delete' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['absent/delete', 'id'=>$model->id], [
                                'title' => Yii::t('app', 'absent-delete'),
                                'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                'data-method'  => 'post',
                    ]);
                }

            ],
    
        ],
    ],
]); ?>
</div>
<?php
$script = <<< JS
    $('#print-user-detail').on('click', function(){
        $('.filters').addClass('no-print');
        //var source=$( '#user-detail-grid' ).clone( true );
        //source.find("tr").eq(3).nextAll().remove();
        window.print();
    });
JS;
$this->registerJs($script);
?>
